version: 2
jobs:
  build:
    docker:
      - image: maxmcd/webtty-node-go:latest
    working_directory: /go/src/github.com/maxmcd/webtty
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Branch }}-{{ .Revision }}
            - v1-repo-{{ .Branch }}
            - v1-repo
      - checkout
      - run:
          name: run go tests
          command: |
            set -e
            go get -u github.com/mitchellh/colorstring
            go get -u github.com/pions/webrtc
            go get -u github.com/kr/pty
            go get -u golang.org/x/crypto/ssh/terminal
            go get -u github.com/btcsuite/btcutil/base58
            go get -u golang.org/x/lint/golint
            golint
            go test
            go test ./pkg/sd
      - run:
          name: run npm tests
          command: |
            set -e
            cd ./web-client
            npm install
            npm run build
            npm run test
      - save_cache:
          key: v1-repo-{{ .Branch }}-{{ .Revision }}
          paths:
            - /go/
